---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackazon
spec:
  selector:
    matchLabels:
      app: hackazon
  replicas: 1
  template:
    metadata:
      labels:
        app: hackazon
    spec:
      containers:
      - name: hackazon
        image: ianwijaya/hackazon
        ports:
        - containerPort: 80
        - containerPort: 443
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: hackazon
  labels:
    gslb: "yes"
    #ns: gslb
spec:
  type: NodePort
  ports:
  - targetPort: 80
    port: 80
    protocol: TCP
  selector:
    app: hackazon

#Self Signed Cert - Do not use when using cert in hostrule block
# ---
#
# apiVersion: v1
# kind: Secret
# metadata:
#   name: bs1-tls
#   namespace: default
# data:
#   tls.crt: |-
#       LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURzekNDQXB1Z0F3SUJBZ0lKQUwxV245RUFyU2oxTUEwR0NTcUdTSWIzRFFFQkN3VUFNR2N4Q3pBSkJnTlYKQkFZVEFsVlRNUlV3RXdZRFZRUUhEQXhFWldaaGRXeDBJRU5wZEhreEhEQWFCZ05WQkFvTUUwUmxabUYxYkhRZwpRMjl0Y0dGdWVTQk1kR1F4SXpBaEJnTlZCQU1NR2lvdWIyTndNREV1WVhacFpHVnRieTUyYlhkaGNtVXVZMjl0Ck1CNFhEVEl3TURreE5URTBNRFl5TUZvWERUSXlNVEl4T1RFME1EWXlNRm93WnpFTE1Ba0dBMVVFQmhNQ1ZWTXgKRlRBVEJnTlZCQWNNREVSbFptRjFiSFFnUTJsMGVURWNNQm9HQTFVRUNnd1RSR1ZtWVhWc2RDQkRiMjF3WVc1NQpJRXgwWkRFak1DRUdBMVVFQXd3YUtpNXZZM0F3TVM1aGRtbGtaVzF2TG5adGQyRnlaUzVqYjIwd2dnRWlNQTBHCkNTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDdWNXRWt4byt5ckhTYVFCRDZyWmFMaW96Yk5qTlcKWHd3bkpkS1E3MjI4YVkzSFVxdW1Mem5pSVMya3ZBU1Ywd1JZc29INmN5U2VjU0lMclo5bXUrTzI5dy9OeXl1WAp1ektWanZWQnRwZWJ1blRmZ1pMbjMxVzA1SXJ3SXhlN3JaZmlsM3ZyQWdsMWZMZ1UxYVFPeGlDRGdYWVRHVzFhCnpzNCtwdkx2MCt2Qk45RTh0S2ppOUFlYnRDdFVseFR5OUFBZVVhR1NlUHEyempwNHVIUnc2dnVFenA0aXJuSWEKSEhJcEEzOEM3UDFCV1pFeXJ3cjFzY2FGV1RVeWZBTmZyOU43a2hyQkQ5VktRWm1xSWp4aXIyb2p5ZlBlN1RNMgo4RG9wYkxNNTJpY2JWL0tyUUxXTjVMQjVON2RueUx2amhwck5SYXZUczFEYlpaT1psYWkraXNWTkFnTUJBQUdqCllqQmdNQjhHQTFVZEl3UVlNQmFBRktjOHlKOTBoQUZ4NVJHVmRJYjBzTUlEbTVhNk1Ba0dBMVVkRXdRQ01BQXcKQ3dZRFZSMFBCQVFEQWdUd01DVUdBMVVkRVFRZU1CeUNHaW91YjJOd01ERXVZWFpwWkdWdGJ5NTJiWGRoY21VdQpZMjl0TUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBQUpXSEllcDR6TkloK3hjVjVia2xiUlRaTHdBSy9vclYyCkxHamUrUGpGdnRCdmFOY3kvNVlKYndVbFBraVpMSlFaN1BPNkZ0UGw1SVNIbHBtMHdGWnk4NXkwb3NIQ01MVEwKQ1VOU3o0YlFmb2tOQzBqRE1hdjBrV0EwczBRL0pvenFGMmJkNTdEblFVb3Z5eGxYcnZzNUszc09sN0hKTWNZKwozazNpSTArNUJuOXpnYjBkMDZwMzBMWUVYblU2Y1dqMzRiMTVDNC9tdXNDN2JyZmtUdGRRNUNlaE5iblRUTllhClFEcDdFSVZURkxkMGhaaVhkR0ovRVVKUmUzM1VMTlNOazVtMnJCL0VldlU3ZEpkVytJbmFEVGplS0VKaVlnUUQKM0Q4LzEwU1RhaUlKUENQamdhWndjVWJWSFlQSzRxa2F0R2E5UGR1cm53a3pSa1d0b1dhQwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
#   tls.key: |-
#       LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3VjV0VreG8reXJIU2EKUUJENnJaYUxpb3piTmpOV1h3d25KZEtRNzIyOGFZM0hVcXVtTHpuaUlTMmt2QVNWMHdSWXNvSDZjeVNlY1NJTApyWjltdStPMjl3L055eXVYdXpLVmp2VkJ0cGVidW5UZmdaTG4zMVcwNUlyd0l4ZTdyWmZpbDN2ckFnbDFmTGdVCjFhUU94aUNEZ1hZVEdXMWF6czQrcHZMdjArdkJOOUU4dEtqaTlBZWJ0Q3RVbHhUeTlBQWVVYUdTZVBxMnpqcDQKdUhSdzZ2dUV6cDRpcm5JYUhISXBBMzhDN1AxQldaRXlyd3Ixc2NhRldUVXlmQU5mcjlON2tockJEOVZLUVptcQpJanhpcjJvanlmUGU3VE0yOERvcGJMTTUyaWNiVi9LclFMV041TEI1TjdkbnlMdmpocHJOUmF2VHMxRGJaWk9aCmxhaStpc1ZOQWdNQkFBRUNnZ0VCQUs0YTF6d2ZPZGk0cXdBeEpVRXM4KzU5OEN2eUlyYjMwbWRZSnBzbGZMN3EKRXVsM3AzNEw4SmV6U1p6N1V4QStOajVZbThYZUdoUlJFZ3ZaMUJoek9zbW9PSXZMVmN6d3Q0SHgxdk1wVEpQUApPMHJBUm1GSzFIM2hCSks4VTdtcmZzWlhMd1RWV1o5N1JUYjJLL0hhNlNTWGw4TmtRM0s0cWJ4NllFbmhsNUdWCmZuRXBVUGFCSWNMWllzYjk0aDEzcmlSelRLUjM5MjZ6Sk1YY2ZjZmplZ2xrV1ppcllJQkVsVGl5cWhPNUk2c0UKYkpCSHR6ejYyNEI2R0RCS3c1Wm9CUlZaQzZVU20rVWgySFFSVEdqckpaRUo0MkNsTDBuQ0poNTE4NmRCMGZUYwpteHRISEE5LzQzMkh2YVVFWW9XcGRtWEZBM3pmSi9RV1hKY3ltVVgzemprQ2dZRUE2R0tMK2hZeUcrYXloblNECm4rRFJVZHVhTmhKY200THpScHIzNEU0dHREWUdjelVLWGRIdk9YbGNkMHc4NSsyeHlVWU93TkhWMkdyV20xNEYKcFI0YlhQYTFEcmVtTG9FbEk4Wk1wdDI5V3l2Nk5uVGxXcXdCMXNsQlkySnNVMUN3V3kxMXZFMlV1dVFZc0xBNQp0aUNUcGRWWkFGeGJjay9yakIxcHZySDU0SjhDZ1lFQXdDdDY4eXFXQWRQcHRYZmRnV2pia2FhQkY2c1U2YUZTClFSekVWRmIxdVNuenAxZmJZbFR5YkVIQkRiOUZGMFoxTVhIYmxjNW54bk9vNGdHWm9idWU3QzFuMzE5UHJRaHgKNUZwS0ltZ1NTbGphREJJMkQxcjNWK2ZxRFp1ZTZyMUVjTGpUMEVPSGwvbWhRNlRKd1NFZlVyN1pLcHdKU1FxbQpUcG1kTjFnSzlwTUNnWUVBd2JsMWk1UjVUWDB5a3BnTEtuc1d4TERYakFBZXA1MnhCTWtubnh4TlNaQklMRDZwClY3RXRSckovZlF4WE1kbWJmbmtpejJlZVovNFl6Z2pCbC9iVFJOcDk4Ymp6bG8wZTB3WDYzSmk1eEltUzIxYnoKNUhURVM3UVhDSzBDTlNwcytuV1pVdE15QytNZkdoeXUzNytrbG5pVzY1QVN3K2NRTEF4UkhTSHRkMjBDZ1lCaQpocWh0L2hxVTYxSjY0TzduaDV4enE3dXFKK1A3K09NVVVTeHoxWFg4cm42bkFNdVJPZDVsRkwxblQvYWJmVnRlCnMzS1M5eFdMMFFiNGdUdUVpWTVzcHNjSDVuVVNVUzhibGhOR1dyZHQrT29xb0RlcFhjbE0vN0duc204akNWRUsKdmlpVE1keFdWZjJSa2U2REgzbFEwbHJEbHViSDFUYjVPNWM0cGVKUkV3S0JnQ2lHbkVOYjIwazhuMGQ1TkZvMQpmMGJpUGRlcFNTOXphRkJRQld5TDFRdjRXakI4TXhCWnR5MnlZbnVnSmR4S1dYK3lFVjV1bEhOSVRoR0xLd2wxCmxBLzNFWmdXcGZZR0l6ekVGWFViS1JOeFhzcEVPR2J0WVZZZGhpWVQ1R1pnNEV0M2crdElaZm45bmprV0JLbzQKTzR0K2M4VHB6SG80Zk4zNHZ4ZW5UN2Q4Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=

# type: kubernetes.io/tls

---
apiVersion: networking.k8s.io/v1
#apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hacknp
  labels:
    gslb: "yes"
spec:
  ingressClassName: avi-lb
  rules:
  - host: hackazon.tkgsingress.livefire.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hackazon
            port:
              number: 80
